version: "3"
services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - '8085:8085'
    expose:
      - '8085'
    depends_on:
      - db
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/spots_system?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: user
    networks:
      - backend

  db:
    image: mysql:5.7
    ports:
      - "3306:3306"
    expose:
      - '3306'
    environment:
      MYSQL_DATABASE: spots_system
      MYSQL_USER: user
      MYSQL_PASSWORD: user
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - kotlin-db-data:/var/lib/mysql
    networks:
      - backend

volumes:
  kotlin-db-data:
networks:
  backend: